apiVersion: v1
kind: Service
metadata:
  name: transpiler
  namespace: transpiler-prod
  labels:
    app: transpiler
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: transpiler
  ports:
    - port: {{ .Values.transpiler.service.servicePorts.port }}
      targetPort: {{ .Values.transpiler.service.servicePorts.targetPort }}
  type: {{ .Values.transpiler.service.type }}