apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: transpiler-prod
type: Opaque
data:
  # Base64 encoded AWS credentials
  AWS_ACCESS_KEY_ID: QVNJQVpZSE43WEk2WEhTSFlJVE8=
  AWS_SECRET_ACCESS_KEY: d1ZHOWNIMVpCVTd0dmtncWFvN1p2ODIzMnhaUVdQbWpudDBmbm9DTQ==
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RUw3Ly8vLy8vLy8vL3dFYURINGdLWWNYOHRyOTJWOXpHU0xXQVZEaS9ESm9uYVlqT09LOTRwUmQ3ZGdTaW95V2N4eFM1STZqTGUraFpiVnU1amZGRmRNQjhPYVVsTTh1UUJxQjVzQStJcVVXVG4xV0NsbWtrNS90VVhldUNleVIzR2F1UEpHdTYzL0dabWVJZU1OcGFGc1NMblV5V2FhRnQ2dEJuZWhQRjdtS0JocTdwUGZ6cTRpLzV6M2dmL2xHdE5SNnVpNXl5WDhKNHNhL1prU0RrcEJ0SVB4WlhEK2s0OFpQb0dER29SNzJTYjhxT2FwVlFVdnpBOTU2dWVlZFhxdURnUEdoR25zeE5rZHNrQ2JkTHM5ZW5QVVZKRTNSNkVrVXRGMmJvQWlvTmliSllpblRXTU54enZDbGwvbTZKSzRvL2RDT3hnWXlNNHhwMWZrK3V2UUpteUt5UVk5YndRNVVLd29sdjFlM1NrM0N4U2s4QlIwc0wyRDdTQkhXKzcvRUkzQ0I4SW5pdSs0YUR3PT0=
  AWS_REGION: dXMtZWFzdC0x
