apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: transpiler-prod
type: Opaque
data:
  # Base64 encoded AWS credentials - Updated with fresh credentials
  AWS_ACCESS_KEY_ID: QVNJQVpZSE43WEk2UjM1SVdXUzc=
  AWS_SECRET_ACCESS_KEY: dmRGMUlLWEVPY2Vuem1hVE1KN3cwaWJCclJpMUluaElINXIvNnZxVA==
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RUFnYURJMGszeDk0QkZOQVhZS3NYeUxXQWVtUVN6ZTVXOFp4cHB2cUF6WlZMV1ZBZnJyYnFDOUZLYXU0Tng5V3I4WEpvbVFvMTd6MmxwaWEwZWxZZjNseVZkckJTaG9lTnhzZlUzbSt4QW5GRTVkZjVUcitPY3VNanlzaEZwZnZNeHR3VkxWK1hDSG4xVjVrcnQ0TFZJcS8rdmpXb01sK05aaGtzOUFLcHc5VHY4MG1SNkdValVIK01nUzJHTDhqRXMvWUdIL05qM2doSDlBSVljdVRWa0hMWHd0VUc2UWhYM3p0T2hGWEt4SmJOSmtrcE0yYzB4aFgyMmdHNCtrazhJcG1aQXBwSjVYVGZMYnFKTEtZeTNwbW9FL0ZmNjNGdmExTGQ5Ulh1c2NiRVc0ZnZpakJQUElvMStHZXhnWXlNNWNVQXFrYUlsYmFPa3hFVUkzQ3FNakVFdnR4aTloZVRXYUJ4aU9IMU82VVhJRzlHUHJYR1JMcjNhbUVCNGpGRWlVbDBRPT0=
  AWS_REGION: dXMtZWFzdC0x
