apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: transpiler-prod
type: Opaque
data:
  # Base64 encoded AWS credentials - Updated with fresh credentials
  AWS_ACCESS_KEY_ID: QVNJQVpZSE43WEk2N09OVDdPQVk=
  AWS_SECRET_ACCESS_KEY: Sm9mRmZhbHIzTHVIMzRISERCcExwNmlZcUtNa1piUlJGNlltOXY4VA==
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RURZYURDVVBOWEh3ZUZ4WHU1QVM5eUxXQVE4c21lb0tGdytwWDkwZmx6aFppTXh3VGFLT0FIaWJ5b0cvT2NPUnl4WmxNNnhRVWZlRU1kVjJMZ2VaK2lmM05vb2xNSmxpSVVFOGJDazhXOVI4TzNNNE12NGxMNS9HaVFwd2hwUFlHSWFrc1hOZVJYanFZb3RBT0d6c1ltQ2VhWWpUeVZiYUNXQTZGbkZEekliMVFYWTBaa25jdVZZbWRrZEFnRnUvS0ZYVjNWdGxyR1ZQU3VTVVR3UjZwcmJNbkxRQ0R0TDFCU1E3ZnBzcVdRN2VHVUJOVFgxRk0vWDVYWGJZeFIzeDVBWUJlWVNUTW9NRjRGZXNqUXQ0VXkyNE45bkp4aFoyRk54Vm1KRDB2WFBQTXdybEhodzRQWE1vOVA2b3hnWXlNMHNyMldCNWJiNGFmSndPODViYUNXNFB1UmRmaG1rOHhsaUpGbHdDSE9abFVYTnB1OTIva2g5bFNFUHNhZ1NaS3RKUnpnPT0=
  AWS_REGION: dXMtZWFzdC0x
