apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: transpiler-prod
type: Opaque
data:
  # Base64 encoded AWS credentials - Updated with new session token
  AWS_ACCESS_KEY_ID: QVNJQVpZSE43WEk2UVVKSFQyRkU=
  AWS_SECRET_ACCESS_KEY: b0xlQjZlaTRML0hrZ0c5TTBzb3Y4M1E3WXhTSTBmcE1sUDh5UFNIRQ==
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RUs3Ly8vLy8vLy8vL3dFYURManhYSFlwMXhScld4MzNweUxXQVlLUXlsbitCcFpqUlVHa3ZXckJpME5iUVZUMGI0b2Jhc1FuTlc3eGJzbG1IazVhZm9jbDkwYVEvME5PbGNkVkxKWmNuNGpPcytwZnBDdktIa0lobDlLSG5Rbll2Ym83NUtXMWdraFd0Mm9Hc0QyVS8xSDdIRWVJM2RxcU1MS0s4bHNCYmw5WjhCL3JSVkpJYTBJQW5qSnB2ZFRGcnZ2ZWNoSW1Cems3YXV0OTlBTmp3eThpQk9mMU1FU0p4UjY0djJWS3cvd1NEOXEyc2FoYmJaZ3A3OW5SZnFvRjFqaVlGTEtaM3BycERuamFhc1RuSldjYzdPd1c5Y21vNTlSeEhPMTRqTFJITDZITEpJWlM0Zi9vd2Q2ajBDL2tvaFlvd3FyRHhnWXlNK0w0djYwMGFrMWVsaWloQ0ZrY0RMVEt5K3I1WTZ0YTRyZmdveHYwVkZEWXdEY2V5NEVVR0k5anJPWG1iN09XWndzUFBBPT0=
  AWS_REGION: dXMtZWFzdC0x
