apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: transpiler-prod
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.servicePorts.port }}
      targetPort: {{ .Values.redis.servicePorts.targetPort}}
  type: ClusterIP